=== UoM-Podcast/weblounge/src/main/resources/xsd/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.o2it.ch/weblounge/3.0/module" xmlns="http://www.o2it.ch/weblounge/3.0/module"
	elementFormDefault="qualified">

	<!-- definition of simple types -->
	<xsd:simpleType name="stringtype">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="timedurationtype">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="idtype">
		<xsd:restriction base="xsd:string" />
	</xsd:simpleType>

	<xsd:simpleType name="booleantype">
		<xsd:restriction base="xsd:boolean" />
	</xsd:simpleType>


	<!--  definition of complex types -->
	<xsd:complexType name="linktype">
		<xsd:attribute name="href" type="xsd:string" use="required" />
		<xsd:attribute name="type" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="scripttype">
		<xsd:attribute name="src" type="xsd:string" use="required" />
		<xsd:attribute name="type" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="includestype">
		<xsd:sequence>
			<xsd:element name="link" type="linktype"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="nametype">
		<xsd:attribute name="language" type="xsd:language" />
	</xsd:complexType>

	<xsd:complexType name="pagelettype">
		<xsd:all>
			<xsd:element name="renderer" type="xsd:anyURI" />
			<xsd:element name="editor" type="xsd:anyURI" />
			<xsd:element name="recheck" type="xsd:duration" />
			<xsd:element name="valid" type="xsd:duration" />
			<xsd:element name="name" type="nametype" />
			<xsd:element name="includes" type="includestype" />
		</xsd:all>
		<xsd:attribute name="id" type="xsd:ID" use="required" />
		<xsd:attribute name="composable" type="xsd:boolean" />
	</xsd:complexType>
	
	<xsd:complexType name="pageletstype">
		<xsd:all>
			<xsd:element name="pagelet" type="pagelettype" minOccurs="0" />
		</xsd:all>
	</xsd:complexType>

	<xsd:complexType name="moduletype">
		<xsd:all>
			<xsd:element name="enable" type="xsd:boolean" />
			<xsd:element name="name" type="nametype" />
		</xsd:all>
		<xsd:attribute name="id" type="xsd:ID" use="required" />
	</xsd:complexType>

	<xsd:element name="module" type="moduletype" />

</xsd:schema>

=== UoM-Podcast/weblounge/src/main/resources/site/modules/text/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="text" xmlns="http://www.o2it.ch/weblounge/3.0/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.o2it.ch/weblounge/3.0/module http://www.o2it.ch/xsd/weblounge/3.0/module.xsd">

  <enable>true</enable>

  <name>Text</name>

  <pagelets>

    <pagelet id="title" composeable="true">
      <name>Title</name>
      <renderer>file://${module.root}/jsp/title/title.jsp</renderer>
      <renderer type="feed">file://${module.root}/jsp/title/title-feed.jsp</renderer>
      <preview>first</preview>
    </pagelet>

    <pagelet id="subtitle" composeable="true">
      <name>Subtitle</name>
      <renderer>file://${module.root}/jsp/subtitle/subtitle.jsp</renderer>
    </pagelet>

    <pagelet id="paragraph" composeable="true">
      <name>Paragraph</name>
      <renderer>file://${module.root}/jsp/paragraph/paragraph.jsp</renderer>
      <renderer type="feed">file://${module.root}/jsp/paragraph/paragraph-feed.jsp</renderer>
    </pagelet>

  </pagelets>

</module>

=== UoM-Podcast/weblounge/src/main/resources/site/modules/repository/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="repository" xmlns="http://www.entwinemedia.com/weblounge/3.0/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/module http://www.entwinemedia.com/xsd/weblounge/3.0/module.xsd">
  <enable>true</enable>
  <name>File repository / Images</name>
  <pagelets>
    <pagelet id="download" composeable="true">
      <name>Download</name>
      <renderer>file://${module.root}/jsp/download/download.jsp</renderer>
    </pagelet>
    <pagelet id="image" composeable="true">
      <name>Image</name>
      <renderer>file://${module.root}/jsp/image/image.jsp</renderer>
      <renderer type="feed">file://${module.root}/jsp/image/image.jsp</renderer>
    </pagelet>
    <pagelet id="gallery" composeable="true">
      <name>Image gallery</name>
      <renderer>file://${module.root}/jsp/gallery/gallery.jsp</renderer>
    </pagelet>
    <pagelet id="gallery_1x1" composeable="false">
      <name>Image gallery 1x1</name>
      <renderer>file://${module.root}/jsp/gallery/gallery_1x1.jsp</renderer>
    </pagelet>
    <pagelet id="gallery_3x3" composeable="false">
      <name>Image gallery 3x3</name>
      <renderer>file://${module.root}/jsp/gallery/gallery_3x3.jsp</renderer>
    </pagelet>
  </pagelets>
</module>

=== UoM-Podcast/weblounge/modules/weblounge-test/src/main/resources/site/modules/navigation/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="navigation" xmlns="http://www.entwinemedia.com/weblounge/3.2/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.2/module http://www.entwinemedia.com/xsd/weblounge/3.2/module.xsd">

  <enable>true</enable>
  <name>Navigation</name>

  <pagelets>

    <pagelet id="link" composeable="true">
      <name>Link</name>
      <renderer>file://${module.root}/jsp/link/link.jsp</renderer>
      <editor>file://${module.root}/jsp/link/link_editor.jsp</editor>
      <includes>
        <link use="editor" href="file://${module.root}/jsp/link/link.css" rel="stylesheet" type="text/css"></link>
        <script use="editor" src="file://${module.root}/jsp/link/link.js" type="text/javascript"></script>
      </includes>
    </pagelet>

    <pagelet id="linklist" composeable="true">
      <name>Link list</name>
      <renderer>file://${module.root}/jsp/linklist/list.jsp</renderer>
      <editor>file://${module.root}/jsp/linklist/list_editor.jsp</editor>
      <recheck>1H</recheck>
      <valid>2H</valid>
    </pagelet>

  </pagelets>

</module>

=== UoM-Podcast/weblounge/src/main/resources/site/modules/navigation/module.xml
<?xml version="1.0" encoding="UTF-8"?>
<module id="navigation" xmlns="http://www.entwinemedia.com/weblounge/3.0/module" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.entwinemedia.com/weblounge/3.0/module http://www.entwinemedia.com/xsd/weblounge/3.0/module.xsd">

  <enable>true</enable>
  <name>Navigation</name>

  <pagelets>
    <pagelet id="link" composeable="true">
      <name>Link</name>
      <renderer>file://${module.root}/jsp/link/link.jsp</renderer>
      <editor>file://${module.root}/jsp/link/link_editor.jsp</editor>
      <includes>
        <link use="editor" href="/weblounge-sites/weblounge-test/modules/navigation/jsp/link.css" type="text/css"></link>
        <script use="editor" src="/weblounge-sites/weblounge-test/modules/navigation/jsp/link.js" type="javascript"></script>
      </includes>
    </pagelet>
  </pagelets>

</module>
